### PR TITLE
Allow custom draw, hide, show, onAdd, and onRemove methods for ClusterIcon (v2)

### PR DESCRIPTION
**Pull request by rognstad**
Here's another try at pull request #42 

----------------------------------------

As I mentioned in issue #41, I am customizing the look of clusters beyond what can be accomplished with CSS. I'm using SVGs to create a pie/donut chart that shows the proportions of various types of markers in a cluster.

These modifications to the MarkerClusterer allow me to specify my own functions to be used for essential ClusterIcon methods, so I can create/update/destroy the SVGs as necessary.

### CODE REVIEW

**Comment by rognstad** [comment]
@Remo, here's a new PR. Would you like me to make an example using custom clusters?

**Comment by Remo** [comment]
@rognstad an example would be nice, but please note that the documentation resides in the `gh-pages` branch. You might run into a problem for which I haven't found a nice solution yet though. Maybe you know more about jekyll than I do ;-) https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/issues/28

**Comment by Remo** [comment]
We should also add the new methods to the reference in `gh-pages`, if you have a minute, otherwise I'll try to have a look tomorrow.

**Comment by brechtpm** [comment]
Is this feature considered stable? Because while these event do appear on the [documentation site](https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/), they don't appear to be officially released yet.

**Comment by Remo** [comment]
@brechtpm yes, you're right, there's no official tag yet.
@XmlmXmlmX can you release this on npm?

**Comment by XmlmXmlmX** [comment]
Ok, I will do my best to get this done this week.

**Comment by XmlmXmlmX** [comment]
Done :)

**Pull request merged**
