### PR TITLE
Add support for backgroundSize property

### PR DESCRIPTION
**Pull request by brechtpm**
This makes it possible to dynamically scale icons.

### CODE REVIEW

**Comment by XmlmXmlmX** [comment]
Is it really a good idea to add each css property after another. How many CSS properies does exists? Wouldn't it be easier and more pragmatic to use the [`cssClass`](https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/blob/master/src/markerclusterer.js#L111) option and style everything in `CSS` rather than in `JS`?

**Comment by brechtpm** [comment]
Makes sense, but that would make it a breaking change I guess? 

I just added this one because I have a specific use case for this property and it's a simple non-breaking change. If other have use cases for different CSS properties it might be worth the breaking change though.

**Comment by Remo** [comment]
@brechtpm why would it be a breaking change? I don't think he wants to remove the existing options. From what I understand (and agree with), he just wants to use `cssClass` instead of having a ton of new CSS properties.

**Comment by brechtpm** [comment]
Right, the already supported properties can stay part of the API while adding `cssClass`, which would retain backwards compatibility. 

When using the `cssClass` approach though, I'd expect my CSS to be the source of truth for styling my markers. The current API though does support a couple of styling properties (for example `textSize` and `backgroundPosition`), which would overrule the CSS. So further down the line I'd probably choose to refactor this to only support styling through CSS. That's the breaking change I was thinking of.

**Comment by Remo** [comment]
Yes I see what you mean, but for now I'd only deprecate it and maybe remove it in the far far future.

**Comment by Remo** [comment]
@brechtpm from what I understand `cssClass` should work fine for you. Going to close this as we have a solution. Please let me know in case I've missed anything!

**Pull request closed without merging**
